### ISSUE TITLE
shipping issues again

### ISSUE THREAD

**Issue by floorz-n-more** [numinix/shipping_boxes_manager#3]
im only testing on 1 product, but when i add this to cart. http://floorz-n-more.com/TESTSITE/index.php?main_page=product_info&products_id=5245
it is going past max package weight when i exceed max package weight. put 1 in cart, versus 5 than 76
thankyou
jimmie

**Comment by floorz-n-more** [comment]
anything

**Comment by jefflew** [comment]
That is the default Zen Cart system.  With shipping boxes manager it goes by the dimensions of your available shipping boxes and will use those to create additional packages if needed.  If you need to also set a maximum weight that a box can carry, we will need to custom program that for you.  Please contact support@numinix.com for an estimate.

**Comment by floorz-n-more** [comment]
So when does Enter the Maximum Package Weight you will ship, which is set in shipping/packaging in configuration. Work.

**Comment by jefflew** [comment]
It is only used for shipments that do not go through shipping boxes manager.  For example, if you do not add dimensions to a product, it will use the default Zen Cart system which splits packages using the maximum weight value.
