### ISSUE TITLE
is this normal behavior

### ISSUE THREAD

**Issue by floorz-n-more** [numinix/shipping_boxes_manager#4]
when a 1 x ready to ship (44 Lbs. 12 x 12 x 12) is in  cart.  fedex ups and usps all show 1 x 44 Lbs, as weight. When i add another ready to ship (or any other package) lets say (3 Lbs) 6 x 6 x 6.  fedex ups and usps all show 2 x 23.50 Lbs, as weight. Should be 2 packages 44 Lbs 12 x 12 x 12 and 3 Lbs 6 x 6 x 6
does the same thing with this section commented out
//$shipping_num_boxes = sizeof($packed_boxes);
      //$shipping_weight = round(($this->total_weight / $shipping_num_boxes), 2); // use our number of packages rather than Zen Cart's calculation, package weight will still have to be an average since we don't know which products are in the box.

**Comment by jefflew** [comment]
Hopefully you mean 23.5lbs.  That's correct since that's the average for 2
packages. The free plugin could be improved though to identify which
products are within each package instead of just an average.  Not just
ready to ship but all packages.

**Comment by floorz-n-more** [comment]
The package for three lbs is being charged for 20.5 extra lbs. 

how much for a complete shipping boxes manager. A total price, not a hourly fee

1 to add max weight per package

2. to know which boxes shipped with which company. EX. Ready to ship ships fedex small items ship usps

3. to send and show the correct weights per box

thankyou

**Comment by floorz-n-more** [comment]
And this part inflates the weight

$sba_box_cubic = $packed_box['width']*$packed_box['height']*$packed_box['length'];

            $sba_shipping_weight = ceil($sba_box_cubic/139) + $sba_shipping_weight;

I have to mod it like this

            $sba_shipping_weight =  $sba_shipping_weight;

**Comment by floorz-n-more** [comment]
6 items each measure 4 x 4 x 2. I have all kinds of boxes entered and it will put 6 in my largest box, and I know I can fit them in other boxes

**Comment by jefflew** [comment]
Are you using the latest version?

Yes, that's the dimensional weight.

Please contact support@numinix.com and we'll provide you with a quote.
